version: '3.8'
services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Aa1234567890
      POSTGRES_DB: rssagg_db
    ports:
      - "8101:5432"

  db_mgmt:
    image: dpage/pgadmin4:7.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rssagg.com
      PGADMIN_DEFAULT_PASSWORD: Aa1234567890
    ports:
      - "8102:80"
    depends_on:
      - db