@path=v1/feed_follows

POST {{url}}/{{path}}
Content-Type: application/json
Authorization: {{token}}

{
    "feedId": "d02ab474-e11c-4c62-a662-9cfbc8057cfa"
}

###

GET {{url}}/{{path}}
Content-Type: application/json
Authorization: {{token}}

###

DELETE  {{url}}/{{path}}/6b1bcb40-77b2-49fe-8f68-212903f5aa1e
Content-Type: application/json
Authorization: {{token}}

###