@path=v1/feed_follows

POST {{url}}/{{path}}
Content-Type: application/json
Authorization: {{token}}

{
    "feedId": "410937a0-aa58-4de5-9639-5ba1e8498411"
}

###

GET {{url}}/{{path}}
Content-Type: application/json
Authorization: {{token}}

###

DELETE  {{url}}/{{path}}/56b0f966-33f8-4a81-93cd-97fd838c38ca
Content-Type: application/json
Authorization: {{token}}

###