@path=v1/feed_follows

POST {{url}}/{{path}}
Content-Type: application/json
Authorization: {{token}}

{
    "feedId": "31e76e7a-13ab-4bf4-a2ef-47f079fb3df7"
}

###

GET {{url}}/{{path}}
Content-Type: application/json
Authorization: {{token}}

###

DELETE  {{url}}/{{path}}/6b1bcb40-77b2-49fe-8f68-212903f5aa1e
Content-Type: application/json
Authorization: {{token}}

###