@path=v1/feeds

POST {{url}}/{{path}}
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Lane's blog",
    "url": "https://www.wagslane.dev/index.xml"
}

# Another valid request:
# {
#     "name": "Boot dev's blog",
#     "url": "https://blog.boot.dev/index.xml"
# }

###

GET {{url}}/{{path}}
Content-Type: application/json

###